language: python
python:
  - "3.6"

install:
  - pip install Flask-WhooshAlchemyPlus==0.7.4 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

services:
  - postgresql

env:
  global:
    - SECRET='sddsdwejernefnbfbhejwjfjfjwjnd'
    - CODECOV_TOKEN="7e24811e-44f3-4ae0-b6a7-2f8897dfa3b9"

before_script:
  - psql -c 'CREATE DATABASE test_swimsafe;' -U postgres 

#Command to run tests
script:
  - nosetests --with-coverage --cover-tests
  - coverage report

after_success:
  - coveralls
  - codecov